version: "3.8"
networks:
  php_pro:
    driver: bridge


services:
  app:
    image: "php:8.3-apache"
    restart: always
    ports:
      - "8081:80" # apache http: 80 https: 443
    volumes:
      - .:/var/www/html
    networks:
      - php_pro
  database:
    image: "mysql:8"
    restart: always
    ports:
      - "33061:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_05_advance
    networks:
      - php_pro