version: "3.8"
networks:
  php_pro:
    driver: bridge


services:
  app:
    image: "php:8.3-apache"
    restart: always
    ports:
      - "8081:80" # apache http: 80 https: 443
    volumes:
      - .:/var/www/html
    networks:
      - php_pro

  database:
    image: "mysql:8"
    restart: always
    ports:
      - "33061:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php_05_advance
    networks:
      - php_pro

  apache:
    image: httpd:latest
    container_name: my-apache-app
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
    networks:
      - php_pro

  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - php_pro